
import { KillStat, EarningStat } from './types';

// LAFF Stats based on provided images
export const LAFF_STATS: KillStat[] = [
  { rank: 1, player: "Zetsu9", team: "Antisocial", totalKills: 150, matches: 48, kpg: 3.12, events: "LAFF" },
  { rank: 2, player: "Neywp", team: "OUTPLAY ESPORTS", totalKills: 129, matches: 48, kpg: 2.69, events: "LAFF" },
  { rank: 3, player: "Igor7", team: "XLD", totalKills: 121, matches: 48, kpg: 2.52, events: "LAFF" },
  { rank: 4, player: "Addy7", team: "Antisocial", totalKills: 120, matches: 47, kpg: 2.55, events: "LAFF" },
  { rank: 5, player: "Sam7:)", team: "OUTPLAY ESPORTS", totalKills: 117, matches: 48, kpg: 2.44, events: "LAFF" },
  { rank: 6, player: "LIPPE!", team: "XLD", totalKills: 116, matches: 48, kpg: 2.42, events: "LAFF" },
  { rank: 7, player: "JNmvp7", team: "OUTPLAY ESPORTS", totalKills: 114, matches: 48, kpg: 2.38, events: "LAFF" },
  { rank: 8, player: "Wii7", team: "MG7 Esports", totalKills: 110, matches: 48, kpg: 2.29, events: "LAFF" },
  { rank: 9, player: "Kazuma", team: "Civis", totalKills: 105, matches: 48, kpg: 2.19, events: "LAFF" },
  { rank: 10, player: "Keven7", team: "Alien", totalKills: 104, matches: 48, kpg: 2.17, events: "LAFF" },
  { rank: 11, player: "DREY22", team: "Line 10", totalKills: 102, matches: 48, kpg: 2.13, events: "LAFF" },
  { rank: 12, player: "GUIFOX7", team: "Line 10", totalKills: 101, matches: 48, kpg: 2.10, events: "LAFF" },
  { rank: 13, player: "Delta", team: "Alien", totalKills: 98, matches: 46, kpg: 2.13, events: "LAFF" },
  { rank: 14, player: "Gbtrem22", team: "MG7 Esports", totalKills: 96, matches: 48, kpg: 2.00, events: "LAFF" },
  { rank: 15, player: "ousado7", team: "Antisocial", totalKills: 94, matches: 47, kpg: 2.00, events: "LAFF" },
  { rank: 16, player: "Master77", team: "Alien", totalKills: 92, matches: 46, kpg: 2.00, events: "LAFF" },
  { rank: 17, player: "Socax7", team: "Teresina eSports", totalKills: 89, matches: 48, kpg: 1.85, events: "LAFF" },
  { rank: 18, player: "GOABE7", team: "SIX EIGHT", totalKills: 88, matches: 48, kpg: 1.83, events: "LAFF" },
  { rank: 19, player: "VianaW", team: "Line 10", totalKills: 88, matches: 48, kpg: 1.83, events: "LAFF" },
  { rank: 20, player: "KKKnalha", team: "DR3 PIT", totalKills: 87, matches: 48, kpg: 1.81, events: "LAFF" },
  { rank: 21, player: "YATO7", team: "SIX EIGHT", totalKills: 84, matches: 48, kpg: 1.75, events: "LAFF" },
  { rank: 22, player: "Itzking1", team: "XLD", totalKills: 84, matches: 48, kpg: 1.75, events: "LAFF" },
  { rank: 23, player: "YannxD", team: "Seven Esports", totalKills: 83, matches: 48, kpg: 1.73, events: "LAFF" },
  { rank: 24, player: "JOKER7", team: "SIX EIGHT", totalKills: 83, matches: 48, kpg: 1.73, events: "LAFF" },
  { rank: 25, player: "bad9", team: "MG7 Esports", totalKills: 83, matches: 48, kpg: 1.73, events: "LAFF" },
  { rank: 26, player: "tatu13", team: "Teresina eSports", totalKills: 81, matches: 48, kpg: 1.69, events: "LAFF" },
  { rank: 27, player: "Seupai", team: "A NOVA ORDEM", totalKills: 79, matches: 47, kpg: 1.68, events: "LAFF" },
  { rank: 28, player: "ISOPOR21", team: "Civis", totalKills: 78, matches: 48, kpg: 1.63, events: "LAFF" },
  { rank: 29, player: "Brisa7", team: "OUTPLAY ESPORTS", totalKills: 77, matches: 45, kpg: 1.71, events: "LAFF" },
  { rank: 30, player: "Lucca7", team: "Seven Esports", totalKills: 77, matches: 46, kpg: 1.67, events: "LAFF" },
  { rank: 31, player: "Batata9", team: "MG7 Esports", totalKills: 75, matches: 41, kpg: 1.83, events: "LAFF" },
  { rank: 32, player: "Kingz", team: "A NOVA ORDEM", totalKills: 73, matches: 42, kpg: 1.74, events: "LAFF" },
  { rank: 33, player: "whyzerxD", team: "DR3 PIT", totalKills: 72, matches: 48, kpg: 1.50, events: "LAFF" },
  { rank: 34, player: "Destroi7", team: "Alien", totalKills: 71, matches: 48, kpg: 1.48, events: "LAFF" },
  { rank: 35, player: "DENE10", team: "Civis", totalKills: 70, matches: 34, kpg: 2.06, events: "LAFF" },
  { rank: 36, player: "GhosTbb", team: "Fury United", totalKills: 68, matches: 36, kpg: 1.89, events: "LAFF" },
  { rank: 37, player: "YOKO7", team: "Teresina eSports", totalKills: 63, matches: 48, kpg: 1.31, events: "LAFF" },
  { rank: 38, player: "KL", team: "Seven Esports", totalKills: 63, matches: 41, kpg: 1.54, events: "LAFF" },
  { rank: 39, player: "Roni", team: "DR3 PIT", totalKills: 62, matches: 48, kpg: 1.29, events: "LAFF" },
  { rank: 40, player: "RochaX", team: "DR3 PIT", totalKills: 62, matches: 48, kpg: 1.29, events: "LAFF" },
  { rank: 41, player: "PH10", team: "AfroGames", totalKills: 57, matches: 36, kpg: 1.58, events: "LAFF" },
  { rank: 42, player: "STREND", team: "ZEAL GG", totalKills: 56, matches: 36, kpg: 1.56, events: "LAFF" },
  { rank: 43, player: "Kaduawp", team: "Maze", totalKills: 56, matches: 36, kpg: 1.56, events: "LAFF" },
  { rank: 44, player: "wpAlan", team: "FLQ E-SPORTS", totalKills: 56, matches: 35, kpg: 1.60, events: "LAFF" },
  { rank: 45, player: "Ângelo7", team: "Antisocial", totalKills: 55, matches: 33, kpg: 1.67, events: "LAFF" },
  { rank: 46, player: "SOUZAFPK", team: "Seven Esports", totalKills: 55, matches: 35, kpg: 1.57, events: "LAFF" },
  { rank: 47, player: "MUNIZ22", team: "Line 10", totalKills: 55, matches: 35, kpg: 1.57, events: "LAFF" },
  { rank: 48, player: "Bolacha", team: "A NOVA ORDEM", totalKills: 53, matches: 42, kpg: 1.26, events: "LAFF" },
  { rank: 49, player: "Flixx9", team: "Maze", totalKills: 48, matches: 36, kpg: 1.33, events: "LAFF" },
  { rank: 50, player: "STAND", team: "XLD", totalKills: 47, matches: 45, kpg: 1.04, events: "LAFF" },
  { rank: 51, player: "SEV7N", team: "Teresina eSports", totalKills: 47, matches: 48, kpg: 0.98, events: "LAFF" },
  { rank: 52, player: "mk7", team: "Civis", totalKills: 46, matches: 33, kpg: 1.39, events: "LAFF" },
  { rank: 53, player: "BALLA7", team: "SIX EIGHT", totalKills: 45, matches: 30, kpg: 1.50, events: "LAFF" },
  { rank: 54, player: "MTZIN", team: "Team Brave Soldiers", totalKills: 44, matches: 36, kpg: 1.22, events: "LAFF" },
  { rank: 55, player: "Quiel.rlq", team: "Team Brave Soldiers", totalKills: 43, matches: 36, kpg: 1.19, events: "LAFF" },
  { rank: 56, player: "Trevor9", team: "Antisocial", totalKills: 42, matches: 17, kpg: 2.47, events: "LAFF" },
  { rank: 57, player: "drk10", team: "Fury United", totalKills: 41, matches: 36, kpg: 1.14, events: "LAFF" },
  { rank: 58, player: "gbzinn7", team: "Fury United", totalKills: 41, matches: 28, kpg: 1.46, events: "LAFF" },
  { rank: 59, player: "RUIVOW", team: "Kings Gaming", totalKills: 41, matches: 34, kpg: 1.21, events: "LAFF" },
  { rank: 60, player: "Bruno7w", team: "ZEAL GG", totalKills: 40, matches: 36, kpg: 1.11, events: "LAFF" },
  { rank: 61, player: "WILL", team: "Golpistas", totalKills: 38, matches: 35, kpg: 1.09, events: "LAFF" },
  { rank: 62, player: "Mthffz", team: "ANGELS", totalKills: 38, matches: 36, kpg: 1.06, events: "LAFF" },
  { rank: 63, player: "JUAN7!", team: "Golpistas", totalKills: 38, matches: 30, kpg: 1.27, events: "LAFF" },
  { rank: 64, player: "DIN1KING", team: "ANGELS", totalKills: 37, matches: 32, kpg: 1.16, events: "LAFF" },
  { rank: 65, player: "LOIROrj", team: "ANGELS", totalKills: 36, matches: 36, kpg: 1.00, events: "LAFF" },
  { rank: 66, player: "KYOTTO", team: "Kings Gaming", totalKills: 36, matches: 35, kpg: 1.03, events: "LAFF" },
  { rank: 67, player: "Nielflx", team: "AfroGames", totalKills: 35, matches: 30, kpg: 1.17, events: "LAFF" },
  { rank: 68, player: "iNoel7", team: "Kings Gaming", totalKills: 35, matches: 36, kpg: 0.97, events: "LAFF" },
  { rank: 69, player: "PLdelas7", team: "Team Brave Soldiers", totalKills: 35, matches: 26, kpg: 1.35, events: "LAFF" },
  { rank: 70, player: "Glaucomsd", team: "AfroGames", totalKills: 34, matches: 30, kpg: 1.13, events: "LAFF" },
  { rank: 71, player: "Liferrr.", team: "ZEAL GG", totalKills: 33, matches: 36, kpg: 0.92, events: "LAFF" },
  { rank: 72, player: "Lobatoy", team: "Seven Esports", totalKills: 32, matches: 22, kpg: 1.45, events: "LAFF" },
  { rank: 73, player: "KLEITIN", team: "Kings Gaming", totalKills: 31, matches: 36, kpg: 0.86, events: "LAFF" },
  { rank: 74, player: "Igz", team: "AfroGames", totalKills: 31, matches: 33, kpg: 0.94, events: "LAFF" },
  { rank: 75, player: "mat11", team: "REDBLUE", totalKills: 31, matches: 28, kpg: 1.11, events: "LAFF" },
  { rank: 76, player: "Gusta10", team: "RHINO E-SPORTS", totalKills: 31, matches: 36, kpg: 0.86, events: "LAFF" },
  { rank: 77, player: "AZY", team: "Maze", totalKills: 29, matches: 24, kpg: 1.21, events: "LAFF" },
  { rank: 78, player: "NICOLAS9", team: "Team Brave Soldiers", totalKills: 28, matches: 35, kpg: 0.80, events: "LAFF" },
  { rank: 79, player: "Raro", team: "ZEAL GG", totalKills: 28, matches: 18, kpg: 1.56, events: "LAFF" },
  { rank: 80, player: "patox7!", team: "RESISTÊNCIA BR", totalKills: 27, matches: 24, kpg: 1.13, events: "LAFF" },
  { rank: 81, player: "Kaka7", team: "REDBLUE", totalKills: 26, matches: 30, kpg: 0.87, events: "LAFF" },
  { rank: 82, player: "Dalpih", team: "RHINO E-SPORTS", totalKills: 26, matches: 33, kpg: 0.79, events: "LAFF" },
  { rank: 83, player: "Mgx88", team: "SIX EIGHT", totalKills: 26, matches: 18, kpg: 1.44, events: "LAFF" },
  { rank: 84, player: "Cruel9", team: "FLQ E-SPORTS", totalKills: 26, matches: 28, kpg: 0.93, events: "LAFF" },
  { rank: 85, player: "roveeX", team: "ZEAL GG", totalKills: 26, matches: 18, kpg: 1.44, events: "LAFF" },
  { rank: 86, player: "Kauãrlq", team: "REDBLUE", totalKills: 25, matches: 36, kpg: 0.69, events: "LAFF" },
  { rank: 87, player: "Gn9", team: "Civis", totalKills: 25, matches: 15, kpg: 1.67, events: "LAFF" },
  { rank: 88, player: "Nepo ign", team: "Golpistas", totalKills: 24, matches: 33, kpg: 0.73, events: "LAFF" },
  { rank: 89, player: "IsackSR", team: "Fury United", totalKills: 23, matches: 29, kpg: 0.79, events: "LAFF" },
  { rank: 90, player: "LeanX", team: "Civis", totalKills: 21, matches: 14, kpg: 1.50, events: "LAFF" },
  { rank: 91, player: "dx7!", team: "RHINO E-SPORTS", totalKills: 21, matches: 18, kpg: 1.17, events: "LAFF" },
  { rank: 92, player: "Biel7", team: "RHINO E-SPORTS", totalKills: 20, matches: 33, kpg: 0.61, events: "LAFF" },
  { rank: 93, player: "Cardoso", team: "FLQ E-SPORTS", totalKills: 19, matches: 36, kpg: 0.53, events: "LAFF" },
  { rank: 94, player: "kauan7", team: "Fury United", totalKills: 19, matches: 15, kpg: 1.27, events: "LAFF" },
  { rank: 95, player: "alan10", team: "REDBLUE", totalKills: 19, matches: 29, kpg: 0.66, events: "LAFF" },
  { rank: 96, player: "YAHULK", team: "Golpistas", totalKills: 16, matches: 19, kpg: 0.84, events: "LAFF" },
  { rank: 97, player: "Baryston", team: "RESISTÊNCIA BR", totalKills: 16, matches: 36, kpg: 0.44, events: "LAFF" },
  { rank: 98, player: "Blessed", team: "FLQ E-SPORTS", totalKills: 15, matches: 28, kpg: 0.54, events: "LAFF" },
  { rank: 99, player: "Luanzz", team: "Maze", totalKills: 15, matches: 12, kpg: 1.25, events: "LAFF" },
  { rank: 100, player: "Akz9", team: "FLQ E-SPORTS", totalKills: 15, matches: 17, kpg: 0.88, events: "LAFF" },
  { rank: 101, player: "LUBILU", team: "Maze", totalKills: 15, matches: 24, kpg: 0.63, events: "LAFF" },
  { rank: 102, player: "HAGANE", team: "Line 10", totalKills: 14, matches: 13, kpg: 1.08, events: "LAFF" },
  { rank: 103, player: "Caue007", team: "Golpistas", totalKills: 14, matches: 21, kpg: 0.67, events: "LAFF" },
  { rank: 104, player: "Seutio.", team: "A NOVA ORDEM", totalKills: 12, matches: 20, kpg: 0.60, events: "LAFF" },
  { rank: 105, player: "Mads9", team: "RESISTÊNCIA BR", totalKills: 12, matches: 36, kpg: 0.33, events: "LAFF" },
];

// Top 100 Real Data based on the provided Liquipedia images
export const KILL_STATS: KillStat[] = [
  { rank: 1, player: "Yago", team: "LOUD", totalKills: 1771, matches: 914, kpg: 1.94, events: "LBFF", lbff1: "- (-)", lbff3: "- (-)", lbff4: "2 (5)", lbff5: "105 (81)", lbff6: "116 (78)", lbff7: "170 (112)", lbff8: "122 (80)", lbff9: "468 (200)", wb2024s1: "187 (96)", wb2024s2: "254 (104)", wb2025s1: "234 (104)", wb2025s2: "113 (54)" },
  { rank: 2, player: "Cauan", team: "LOUD", totalKills: 1642, matches: 1081, kpg: 1.52, events: "LBFF", lbff1: "- (-)", lbff3: "138 (84)", lbff4: "99 (80)", lbff5: "93 (81)", lbff6: "102 (81)", lbff7: "155 (117)", lbff8: "121 (80)", lbff9: "342 (200)", wb2024s1: "189 (96)", wb2024s2: "199 (104)", wb2025s1: "126 (104)", wb2025s2: "78 (54)" },
  // ... rest of the file
